[package]
name = "roll-lib"
version = "0.1.0"
authors = ["Victor Roest <victor@xirion.net>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
rand_core = {version="0.5", features=["getrandom"] }

[dev-dependencies]
bnf = "0.3"
