name: Rust

on: push

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
  wasm:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: jetli/wasm-pack-action@v0.3.0
      with:
        version: 'latest'
    - name: Build
      run: cd wasm && wasm-pack build --target web
    - name: Test
      run: cd wasm && wasm-pack test --node --firefox --chrome --headless
